name: CMake Build

run-name: ${{ github.actor }} invoked build.

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.20.0
  CMAKE_BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    outputs:
      tag: ${{ steps.git.outputs.tag }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows Latest MSVC",
              os: windows-latest,
              cc: "cl", cxx: "cl",
            }
          - {
              name: "Linux Latest GCC",
              os: ubuntu-latest,
              cc: "gcc", cxx: "g++",
            }
          - {
              name: "MacOS Latest Clang",
              os: macos-latest,
              cc: "clang", cxx: "clang++",
            }
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

    - name: Build
      run: cmake --build build

    - name: Test
      run: cd build && ctest -V -C ${{ env.CMAKE_BUILD_TYPE }}
