
name: Build and Test

run-name: ${{ github.actor }} invoked build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CMAKE_VERSION: 3.20.0

jobs:
  build-and-test:
    name: ${{ matrix.config.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}
    outputs:
      tag: ${{ steps.git.outputs.tag }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug, Release ]
        config:
          - {
              name: "Windows Latest MSVC",
              os: windows-latest,
              cc: "cl", cxx: "cl",
            }
          - {
              name: "Linux Latest clang",
              os: ubuntu-24.04,
              cc: "clang", cxx: "clang++",
            }
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      run: cd build && ctest -V -C ${{ matrix.build_type }}
